# Generated by Django 4.2.2 on 2024-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
