# Generated by Django 4.2.2 on 2024-11-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0002_alter_summary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='status',
            field=models.IntegerField(choices=[(0, 'success'), (1, 'running'), (2, 'failure')], default=0),
        ),
    ]
