# Generated by Django 4.2.2 on 2024-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0003_summary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='signal_plot_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
