# Generated by Django 4.2.2 on 2024-11-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0004_summary_signal_plot_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
    ]
