# Generated by Django 4.2.2 on 2025-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0005_alter_summary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
