# Generated by Django 4.2.2 on 2025-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0006_summary_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='ticker',
            field=models.CharField(blank=True, default='AAPL', max_length=10, null=True),
        ),
    ]
