# Generated by Django 4.2.2 on 2025-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0007_summary_last_updated_alter_summary_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='ticker',
            field=models.CharField(blank=True, default='^SPX', max_length=10, null=True),
        ),
    ]
