# Generated by Django 4.2.2 on 2023-06-15 19:01

from django.db import migrations, models
import django.utils.timezone
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='last_updates',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='file',
            field=models.FileField(upload_to=scriptupload.models.script_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.FileField(blank=True, upload_to=scriptupload.models.script_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
