# Generated by Django 4.2.2 on 2023-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0002_script_created_script_last_updates_alter_script_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='last_updates',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
