# Generated by Django 4.2.2 on 2023-06-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0003_alter_script_created_alter_script_last_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='last_updates',
            new_name='last_updated',
        ),
    ]
