# Generated by Django 4.2.2 on 2023-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0004_rename_last_updates_script_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
