# Generated by Django 4.2.2 on 2023-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0006_scriptcategory_alter_script_image_script_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='category',
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='scripts',
            field=models.ManyToManyField(related_name='categories', to='scriptupload.script'),
        ),
    ]
