# Generated by Django 4.2.2 on 2023-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0007_remove_script_category_scriptcategory_scripts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptcategory',
            name='scripts',
        ),
        migrations.AddField(
            model_name='script',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='scriptupload.scriptcategory'),
        ),
    ]
