# Generated by Django 4.2.2 on 2023-09-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0008_remove_scriptcategory_scripts_script_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scriptupload.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='script',
            name='categories',
            field=models.ManyToManyField(to='scriptupload.scriptcategory'),
        ),
    ]
