# Generated by Django 4.2.2 on 2023-09-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0009_scriptcategory_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptcategory',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptupload.scriptcategory'),
        ),
    ]
