# Generated by Django 4.2.2 on 2023-10-31 18:35

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0011_alter_scriptcategory_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=5)),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='IndexConstituents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=5)),
                ('ticker', models.CharField(max_length=5)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OHLCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='script',
            name='file',
            field=models.FileField(storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.script_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.ImageField(blank=True, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.script_file_path),
        ),
    ]
