# Generated by Django 4.2.2 on 2023-10-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0012_indexactions_indexconstituents_ohlcdata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexactions',
            options={'verbose_name': 'Index Action', 'verbose_name_plural': 'Index Actions'},
        ),
        migrations.AlterModelOptions(
            name='indexconstituents',
            options={'verbose_name': 'Index Constituent', 'verbose_name_plural': 'Index Constituents'},
        ),
        migrations.AlterModelOptions(
            name='ohlcdata',
            options={'verbose_name': 'OHLC Data', 'verbose_name_plural': 'OHLC Data'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'verbose_name': 'Script', 'verbose_name_plural': 'Scripts'},
        ),
        migrations.AlterModelOptions(
            name='scriptcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='ohlcdata',
            old_name='close_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='ohlcdata',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ohlcdata',
            old_name='high_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='ohlcdata',
            old_name='low_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='ohlcdata',
            old_name='open_price',
            new_name='open',
        ),
    ]
