# Generated by Django 4.2.2 on 2023-10-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0013_alter_indexactions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexconstituents',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
