# Generated by Django 4.2.2 on 2023-10-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0014_alter_indexconstituents_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexconstituents',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
