# Generated by Django 4.2.2 on 2023-11-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0017_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexActions',
            new_name='IndexAction',
        ),
        migrations.RenameModel(
            old_name='IndexConstituents',
            new_name='IndexConstituent',
        ),
    ]
