# Generated by Django 4.2.2 on 2023-11-15 20:23

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0018_rename_indexactions_indexaction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScriptCategory',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='script',
            name='file',
            field=models.FileField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.script_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.ImageField(blank=True, max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.script_file_path),
        ),
    ]
