# Generated by Django 4.2.2 on 2023-11-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0019_rename_scriptcategory_category_alter_script_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexAction',
        ),
        migrations.DeleteModel(
            name='IndexConstituent',
        ),
        migrations.DeleteModel(
            name='OHLCData',
        ),
    ]
