# Generated by Django 4.2.2 on 2023-11-24 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0020_delete_indexaction_delete_indexconstituent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('day', models.CharField(max_length=1)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptupload.report')),
            ],
        ),
    ]
