# Generated by Django 4.2.2 on 2023-12-02 14:39

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0021_reportemailtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latest_pdf',
            field=models.FileField(blank=True, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.report_file_path),
        ),
    ]
