# Generated by Django 4.2.2 on 2023-12-02 16:41

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0022_report_latest_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latest_pdf',
            field=models.FileField(storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.report_file_path),
        ),
    ]
