# Generated by Django 4.2.2 on 2023-12-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0025_remove_script_categories_script_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scriptupload.category'),
        ),
    ]
