# Generated by Django 4.2.2 on 2023-12-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0026_alter_script_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
