# Generated by Django 4.2.2 on 2023-12-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0027_alter_script_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scriptupload.category'),
        ),
        migrations.AlterField(
            model_name='script',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
