# Generated by Django 4.2.2 on 2023-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0029_alter_category_parent_category_alter_script_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='index_in_category',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
