# Generated by Django 4.2.2 on 2023-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0033_alter_script_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
