# Generated by Django 4.2.2 on 2024-01-30 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scriptupload', '0036_alter_scriptrunresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrunresult',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scriptupload.script'),
        ),
        migrations.AlterField(
            model_name='scriptrunresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
