# Generated by Django 4.2.2 on 2024-01-30 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0037_alter_scriptrunresult_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrunresult',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
