# Generated by Django 4.2.2 on 2024-01-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0038_scriptrunresult_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrunresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
