# Generated by Django 4.2.2 on 2024-01-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0040_script_error_message_script_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='success', max_length=15),
        ),
        migrations.DeleteModel(
            name='ScriptRunResult',
        ),
    ]
