# Generated by Django 4.2.2 on 2024-01-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0041_report_status_delete_scriptrunresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
