# Generated by Django 4.2.2 on 2024-02-19 13:53

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0044_report_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='output_type',
            field=models.CharField(choices=[('plt', 'matplotlib.pyplot'), ('pd', 'pandas')], default='plt', max_length=7),
        ),
        migrations.AddField(
            model_name='script',
            name='table_file',
            field=models.FileField(blank=True, null=True, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.script_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.CharField(default='success', max_length=12),
        ),
    ]
