# Generated by Django 4.2.2 on 2024-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0047_alter_script_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='error_message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='output_type',
            field=models.CharField(choices=[('plt', 'matplotlib.pyplot'), ('pd', 'pandas'), ('pd and plt', 'pandas matplotlib.pyplot')], default='plt', max_length=10),
        ),
    ]
