# Generated by Django 4.2.2 on 2024-02-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0048_alter_script_error_message_alter_script_output_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='output_type',
            field=models.CharField(choices=[('plt', 'matplotlib.pyplot'), ('pd', 'pandas'), ('pd plt', 'pandas matplotlib.pyplot')], default='plt', max_length=10),
        ),
    ]
