# Generated by Django 4.2.2 on 2024-02-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0049_alter_script_output_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='output_type',
            field=models.CharField(choices=[('plt', 'Chart (using matplotlib.pyplot.savefig())'), ('pd', 'Table (using pandas.Dataframe.to_csv())'), ('pd plt', 'Chart and Table')], default='plt', max_length=10),
        ),
    ]
