# Generated by Django 4.2.2 on 2024-03-28 23:19

from django.db import migrations, models
import django.db.models.deletion
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0050_alter_script_output_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data', models.FileField(max_length=20, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.script_file_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Table Data',
                'verbose_name_plural': 'Table Data',
            },
        ),
        migrations.AddField(
            model_name='script',
            name='table_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_of_origin', to='scriptupload.tabledata'),
        ),
    ]
