# Generated by Django 4.2.2 on 2024-03-28 23:33

from django.db import migrations, models
import django.db.models.deletion
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0051_tabledata_script_table_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='table_data',
        ),
        migrations.AddField(
            model_name='tabledata',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='scriptupload.script'),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='csv_data',
            field=models.FileField(max_length=20, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.table_file_path),
        ),
    ]
