# Generated by Django 4.2.2 on 2024-03-28 23:34

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0052_remove_script_table_data_tabledata_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='csv_data',
            field=models.FileField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.table_file_path),
        ),
    ]
