# Generated by Django 4.2.2 on 2024-03-28 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0053_alter_tabledata_csv_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='scriptupload.script'),
        ),
    ]
