# Generated by Django 4.2.2 on 2024-03-30 22:54

from django.db import migrations, models
import django.db.models.deletion
import financeplatform.storage_backends
import scriptupload.models.filepaths


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0054_alter_tabledata_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.chart_file_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('script', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='scriptupload.script')),
            ],
            options={
                'verbose_name': 'Chart Data',
                'verbose_name_plural': 'Chart Data',
            },
        ),
    ]
