# Generated by Django 4.2.2 on 2024-04-14 16:23

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models.filepaths


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0056_remove_script_image_remove_script_table_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='image_file',
            field=models.ImageField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.chart_file_path),
        ),
    ]
