# Generated by Django 4.2.2 on 2024-07-14 18:38

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models.filepaths


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0058_alter_chartdata_image_file_alter_report_latest_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='image_file',
            field=models.ImageField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.chart_file_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='latest_pdf',
            field=models.FileField(blank=True, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.report_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='file',
            field=models.FileField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.script_file_path),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='csv_data',
            field=models.FileField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.table_file_path),
        ),
    ]
