# Generated by Django 4.2.2 on 2024-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0059_alter_chartdata_image_file_alter_report_latest_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
