# Generated by Django 4.2.2 on 2024-09-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0061_alter_chartdata_image_file_alter_report_latest_pdf_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportemailtask',
            unique_together={('report', 'email', 'day')},
        ),
    ]
