# Generated by Django 4.2.2 on 2024-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0062_alter_reportemailtask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemailtask',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday'), ('*', 'Every Day')], max_length=1),
        ),
    ]
