# Generated by Django 4.2.2 on 2024-10-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0063_alter_reportemailtask_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='plotly_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
