# Generated by Django 4.2.2 on 2024-10-20 15:44

from django.db import migrations, models
import financeplatform.storage_backends
import scriptupload.models.filepaths


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0064_chartdata_plotly_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='table_meta',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='image_file',
            field=models.ImageField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.chart_file_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='latest_pdf',
            field=models.FileField(blank=True, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.report_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='file',
            field=models.FileField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.script_file_path),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='csv_data',
            field=models.FileField(max_length=200, storage=financeplatform.storage_backends.PrivateMediaStorage(), upload_to=scriptupload.models.filepaths.table_file_path),
        ),
    ]
