# Generated by Django 4.2.2 on 2024-10-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0065_tabledata_table_meta_alter_chartdata_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='table_meta',
            field=models.JSONField(default=dict),
        ),
    ]
