# Generated by Django 5.1.4 on 2024-12-27 17:37

import scriptupload.models.filepaths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0066_alter_tabledata_table_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='image_file',
            field=models.ImageField(max_length=200, upload_to=scriptupload.models.filepaths.chart_file_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='latest_pdf',
            field=models.FileField(blank=True, upload_to=scriptupload.models.filepaths.report_file_path),
        ),
        migrations.AlterField(
            model_name='script',
            name='file',
            field=models.FileField(max_length=200, upload_to=scriptupload.models.filepaths.script_file_path),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='csv_data',
            field=models.FileField(max_length=200, upload_to=scriptupload.models.filepaths.table_file_path),
        ),
    ]
