# Generated by Django 4.2.2 on 2025-02-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olandinvestmentsapi', '0005_alter_summary_options'),
        ('scriptupload', '0067_script_for_summary_alter_chartdata_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='summaries',
            field=models.ManyToManyField(to='olandinvestmentsapi.summary'),
        ),
    ]
