# Generated by Django 4.2.2 on 2025-03-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0068_report_summaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemailtask',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tasks', to='scriptupload.report'),
        ),
    ]
