# Generated by Django 4.2.2 on 2023-06-29 21:23

from django.db import migrations, models
import django.db.models.deletion
import scriptupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0005_alter_script_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.ImageField(blank=True, upload_to=scriptupload.models.script_file_path),
        ),
        migrations.AddField(
            model_name='script',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scriptupload.scriptcategory'),
        ),
    ]
