# Generated by Django 4.2.2 on 2023-09-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0010_alter_scriptcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scriptupload.scriptcategory'),
        ),
    ]
