# Generated by Django 4.2.2 on 2023-12-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0024_alter_report_latest_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='categories',
        ),
        migrations.AddField(
            model_name='script',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scriptupload.category'),
        ),
    ]
