# Generated by Django 4.2.2 on 2023-12-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0030_script_index_in_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
