# Generated by Django 4.2.2 on 2024-01-30 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scriptupload', '0034_alter_report_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scriptupload.script')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
