# Generated by Django 4.2.2 on 2024-01-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0035_scriptrunresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptrunresult',
            options={'verbose_name': 'Script Run Result', 'verbose_name_plural': 'Script Run Results'},
        ),
    ]
