# Generated by Django 4.2.2 on 2024-01-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0039_alter_scriptrunresult_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='status',
            field=models.CharField(default='success', max_length=15),
        ),
    ]
