# Generated by Django 4.2.2 on 2024-02-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0045_script_output_type_script_table_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'Running'), (2, 'Failure')], default=0),
        ),
    ]
