# Generated by Django 4.2.2 on 2024-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0046_alter_script_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.IntegerField(choices=[(0, 'success'), (1, 'running'), (2, 'failure')], default=0),
        ),
    ]
