# Generated by Django 4.2.2 on 2024-04-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptupload', '0055_chartdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='image',
        ),
        migrations.RemoveField(
            model_name='script',
            name='table_file',
        ),
    ]
