# Generated by Django 4.2.2 on 2025-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickersymbol',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
