# Generated by Django 4.2.2 on 2025-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_tickersymbol_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickersymbol',
            name='symbol',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
