# Generated by Django 4.2.2 on 2023-11-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=5)),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Index Action',
                'verbose_name_plural': 'Index Actions',
            },
        ),
        migrations.CreateModel(
            name='IndexConstituent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=5)),
                ('ticker', models.CharField(max_length=5)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Index Constituent',
                'verbose_name_plural': 'Index Constituents',
            },
        ),
        migrations.CreateModel(
            name='OHLCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=19)),
                ('high', models.DecimalField(decimal_places=4, max_digits=19)),
                ('low', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close', models.DecimalField(decimal_places=4, max_digits=19)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'OHLC Data',
                'verbose_name_plural': 'OHLC Data',
            },
        ),
    ]
