# Generated by Django 4.2.2 on 2023-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('country', models.CharField(max_length=2)),
                ('term', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.AlterField(
            model_name='indexaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='indexconstituent',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ohlcdata',
            name='date',
            field=models.DateField(),
        ),
    ]
