# Generated by Django 4.2.2 on 2023-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0002_rate_alter_indexaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlcdata',
            name='close',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ohlcdata',
            name='high',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ohlcdata',
            name='low',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ohlcdata',
            name='open',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
    ]
