# Generated by Django 4.2.2 on 2023-11-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0003_alter_ohlcdata_close_alter_ohlcdata_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='term',
            field=models.CharField(max_length=6),
        ),
    ]
