# Generated by Django 4.2.2 on 2023-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0004_alter_rate_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlcdata',
            name='close',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ohlcdata',
            name='high',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ohlcdata',
            name='low',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ohlcdata',
            name='open',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
    ]
