# Generated by Django 4.2.2 on 2023-11-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0005_alter_ohlcdata_close_alter_ohlcdata_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
