# Generated by Django 4.2.2 on 2023-12-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0006_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexaction',
            unique_together={('index', 'ticker', 'date', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='indexconstituent',
            unique_together={('index', 'date_added', 'ticker')},
        ),
        migrations.AlterUniqueTogether(
            name='ohlcdata',
            unique_together={('ticker', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('date', 'rate', 'country', 'term')},
        ),
    ]
