# Generated by Django 4.2.2 on 2024-02-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0008_stockexchangedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockexchangedata',
            name='advances_volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='declines_volume',
            field=models.BigIntegerField(),
        ),
    ]
