# Generated by Django 4.2.2 on 2024-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0009_alter_stockexchangedata_advances_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockexchangedata',
            name='advances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='advances_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='declines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='declines_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='new_highs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='new_lows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='total_issues_traded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
