# Generated by Django 4.2.2 on 2024-05-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0010_alter_stockexchangedata_advances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackRockIndexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=72)),
                ('sector', models.CharField(max_length=10)),
                ('weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('notional_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('isin', models.CharField(max_length=15)),
                ('location_of_risk', models.CharField(max_length=15)),
                ('exchange', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=5)),
                ('fx_rate', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'verbose_name': 'BlackRock iShares S&P/TSX Capped Energy Index ETF Data',
                'verbose_name_plural': 'BlackRock iShares S&P TSX',
            },
        ),
    ]
