# Generated by Django 4.2.2 on 2024-06-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0011_blackrockindexdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackrockindexdata',
            name='sector',
            field=models.CharField(max_length=30),
        ),
    ]
