# Generated by Django 4.2.2 on 2024-07-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0012_alter_blackrockindexdata_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blackrockindexdata',
            options={'verbose_name': 'BlackRock iShares ETF data', 'verbose_name_plural': 'BlackRock iShares S&P TSX'},
        ),
        migrations.AddField(
            model_name='blackrockindexdata',
            name='indexticker',
            field=models.CharField(default='XEG', max_length=6),
            preserve_default=False,
        ),
    ]
