# Generated by Django 4.2.2 on 2024-07-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0013_alter_blackrockindexdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blackrockindexdata',
            options={'verbose_name': 'BlackRock iShares ETF data', 'verbose_name_plural': 'BlackRock iShares ETF data'},
        ),
        migrations.AlterUniqueTogether(
            name='blackrockindexdata',
            unique_together={('date', 'ticker', 'indexticker')},
        ),
    ]
