# Generated by Django 4.2.2 on 2024-02-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseinterface', '0007_alter_indexaction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchangeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exchange_name', models.CharField(max_length=6)),
                ('advances', models.IntegerField()),
                ('advances_volume', models.IntegerField()),
                ('declines', models.IntegerField()),
                ('declines_volume', models.IntegerField()),
                ('new_highs', models.IntegerField()),
                ('new_lows', models.IntegerField()),
                ('total_issues_traded', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock Exchange Data',
                'verbose_name_plural': 'Stock Exchange Data',
                'unique_together': {('date', 'exchange_name')},
            },
        ),
    ]
