name: Test Backend on PR

on:
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ca-central-1
  ECR_REPOSITORY: oi-prod-repo
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    environment: Test (Backend)
    defaults:
      run:
        working-directory: backend/
    env:
      SECRET_KEY: ${{ github.sha }}
      DEBUG: True
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.20'
        cache: 'pip'
        cache-dependency-path: 'backend/requirements.txt'

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Migrate Database
      run: python manage.py migrate

    - name: Test Backend
      run : python manage.py test